### ISSUE TITLE
draft an exec meeting agenda

### ISSUE THREAD

**Issue by RobTheOceanographer** [datatas/leadership#11]

**Comment by RobTheOceanographer** [comment]
DataTas Goals:
- 100 members by August 2018
- Increase number of non-IMAS speakers.
- Increase the number of non-IMAS members.

**Comment by RobTheOceanographer** [comment]
Discussion topics:
- Woman in data science symposium
- banners
- stickers
- funding avenues
- TUU's next meeting.
- Secretary arrangements
-

**Comment by bschroeter** [comment]
Done and sent
