### ISSUE TITLE
Get three quotes for banners.

### ISSUE THREAD

**Issue by RobTheOceanographer** [datatas/leadership#2]
Ben is to get some quotes for the production of two DataTas pull up banners.
We would likely leave one banner in the imas foyer full time.

**Comment by RobTheOceanographer** [comment]
Might be able to recycle some banners from UTas/IMAS... Ben is following up.

**Comment by RobTheOceanographer** [comment]
How much was it to get new inserts for the recycled banners? @bschroeter

**Comment by bschroeter** [comment]
175+GST for a reskin.
